function repeatTimes(text,times) {
    var i = times;
	var arr = [];
	while (i > 0) {
		arr.push(text);
		i -= 1;
	}
	return arr
}
window.files.maniaSonicAnimations = {
  "walk":{
    frames:[
      "spr_sonic_26.png",
	  "spr_sonic_27.png",
	  "spr_sonic_28.png",
	  "spr_sonic_29.png",
	  "spr_sonic_30.png",
	  "spr_sonic_31.png",
	  "spr_sonic_32.png",
	  "spr_sonic_33.png",
	  "spr_sonic_34.png",
	  "spr_sonic_35.png",
	  "spr_sonic_36.png",
	  "spr_sonic_37.png"
    ],
    fps:45,
    loop:true
  },
  "jog":{
    frames:[
      "spr_sonic_189.png",
	  "spr_sonic_190.png",
	  "spr_sonic_192.png",
	  "spr_sonic_193.png",
	  "spr_sonic_194.png",
	  "spr_sonic_195.png",
	  "spr_sonic_196.png",
	  "spr_sonic_197.png",
	  "spr_sonic_198.png"
    ],
    fps:45,
    loop:true
  },
  "hurt":{
    frames:[
      "spr_sonic_94.png",
	  "spr_sonic_96.png",
	  "spr_sonic_97.png",
	  "spr_sonic_98.png"
    ],
    fps:60,
    loop:false
  },
  "skid":{
    frames:[
	  "spr_sonic_87.png",
	  "spr_sonic_88.png",
	  "spr_sonic_89.png",
	  "spr_sonic_90.png",
      "spr_sonic_91.png",
	  "spr_sonic_92.png",
	  "spr_sonic_93.png"
    ],
    fps:22,
    loop:false
  },
  "spindash":{
    frames:[
      "spr_sonic_71.png",
	  "spr_sonic_72.png",
	  "spr_sonic_73.png",
	  "spr_sonic_74.png",
	  "spr_sonic_75.png",
	  "spr_sonic_76.png",
	  "spr_sonic_77.png",
	  "spr_sonic_78.png",
	  "spr_sonic_79.png",
	  "spr_sonic_80.png",
	  "spr_sonic_81.png",
	  "spr_sonic_82.png",
	  "spr_sonic_83.png",
	  "spr_sonic_84.png",
	  "spr_sonic_85.png",
	  "spr_sonic_86.png"
    ],
    fps:30,
    loop:true
  },
  "died":{
    frames:[
      "dead.png"
    ],
    fps:60,
    loop:true
  },
  "spring":{
    frames:[
      "spr_sonic_148.png",
	  "spr_sonic_149.png"
    ],
    fps:40,
    loop:true
  },
  "duck":{
    frames:[
      "spr_sonic_67.png",
	  "spr_sonic_68.png",
	  "spr_sonic_69.png",
	  "spr_sonic_70.png"
    ],
    fps:15,
    loop:false
  },
  "lookup":{
    frames:[
      "spr_sonic_62.png",
	  "spr_sonic_63.png",
	  "spr_sonic_64.png",
	  "spr_sonic_65.png",
	  "spr_sonic_66.png"
    ],
    fps:15,
    loop:false
  },
  "stand":{
    frames:repeatTimes("spr_sonic_0.png",60).concat([
		"spr_sonic_1.png",
		"spr_sonic_2.png",
		"spr_sonic_3.png",
		"spr_sonic_4.png",
		/////////////////
		"spr_sonic_5.png",
		"spr_sonic_6.png",
		"spr_sonic_7.png",
		"spr_sonic_8.png",
		"spr_sonic_9.png",
		
		"spr_sonic_5.png",
		"spr_sonic_6.png",
		"spr_sonic_7.png",
		"spr_sonic_8.png",
		"spr_sonic_9.png",
		
		"spr_sonic_5.png",
		"spr_sonic_6.png",
		"spr_sonic_7.png",
		"spr_sonic_8.png",
		"spr_sonic_9.png",
		
		/////////////////
		
		"spr_sonic_10.png",
		"spr_sonic_11.png",
		"spr_sonic_12.png",
		"spr_sonic_13.png",
		"spr_sonic_14.png",
		"spr_sonic_15.png",
		"spr_sonic_16.png",
		"spr_sonic_17.png",
		"spr_sonic_18.png",
		
		"spr_sonic_19.png",
		"spr_sonic_20.png",
		"spr_sonic_21.png",
		"spr_sonic_22.png",
		"spr_sonic_23.png",
		"spr_sonic_24.png",
		"spr_sonic_25.png",
		
		"spr_sonic_19.png",
		"spr_sonic_20.png",
		"spr_sonic_21.png",
		"spr_sonic_22.png",
		"spr_sonic_23.png",
		"spr_sonic_24.png",
		"spr_sonic_25.png",
		
		"spr_sonic_19.png",
		"spr_sonic_20.png",
		"spr_sonic_21.png",
		"spr_sonic_22.png",
		"spr_sonic_23.png",
		"spr_sonic_24.png",
		"spr_sonic_25.png",
		
		"spr_sonic_18.png",
		"spr_sonic_17.png",
		"spr_sonic_16.png",
		"spr_sonic_15.png",
		"spr_sonic_14.png",
		"spr_sonic_13.png",
		"spr_sonic_12.png",
		"spr_sonic_11.png",
		"spr_sonic_5.png",
		"spr_sonic_4.png",
		"spr_sonic_3.png",
		"spr_sonic_2.png",
		"spr_sonic_1.png",
		"spr_sonic_0.png"
	]),
    fps:20,
    loop:true
  },
  "run":{
    frames:[
      "spr_sonic_38.png",
	  "spr_sonic_39.png",
	  "spr_sonic_40.png",
	  "spr_sonic_41.png",
	  "spr_sonic_42.png",
	  "spr_sonic_43.png",
	  "spr_sonic_45.png"
    ],
    fps:30,
    loop:true
  },
  "runfastest":{
    frames:[
      "spr_sonic_185.png",
	  "spr_sonic_186.png",
	  "spr_sonic_187.png",
	  "spr_sonic_188.png"
    ],
    fps:30,
    loop:true
  },
  "push":{
    frames:[
      "spr_sonic_117.png",
	  "spr_sonic_118.png",
	  "spr_sonic_119.png",
	  "spr_sonic_120.png",
	  "spr_sonic_122.png",
	  "spr_sonic_123.png",
	  "spr_sonic_124.png",
	  "spr_sonic_125.png",
	  "spr_sonic_126.png"
    ],
    fps:13,
    loop:true
  },
  "roll":{
    frames:[
      "spr_sonic_46.png",
	  "spr_sonic_47.png",
	  "spr_sonic_48.png",
	  "spr_sonic_49.png",
	  "spr_sonic_50.png",
	  "spr_sonic_51.png",
	  "spr_sonic_52.png",
	  "spr_sonic_53.png",
	  "spr_sonic_54.png",
	  "spr_sonic_55.png",
	  "spr_sonic_56.png",
	  "spr_sonic_57.png",
	  "spr_sonic_58.png",
	  "spr_sonic_59.png",
	  "spr_sonic_60.png",
	  "spr_sonic_61.png"
    ],
    fps:60,
    loop:true
  }
};