window.files.maniaSonicAnimations = {
  "walk":{
    frames:[
      "walk1.png",
      "walk2.png",
      "walk3.png",
      "walk4.png",
      "walk5.png",
      "walk6.png",
      "walk7.png",
      "walk8.png",
      "walk9.png",
      "walk10.png",
      "walk11.png",
      "walk12.png"
    ],
    fps:20,
    loop:true
  },
  "hurt":{
    frames:[
      "hurt1.png",
      "hurt2.png"
    ],
    fps:60,
    loop:true
  },
  "skid":{
    frames:[
      "brake1.png",
      "brake2.png"
    ],
    fps:60,
    loop:true
  },
  "spindash":{
    frames:[
      "spindash1.png",
      "spindash-mid.png",
      "spindash2.png",
      "spindash-mid.png",
      "spindash3.png",
      "spindash-mid.png",
      "spindash4.png",
      "spindash-mid.png",
      "spindash5.png",
      "spindash-mid.png",
      "spindash6.png",
      "spindash-mid.png",
      "spindash7.png",
      "spindash-mid.png",
      "spindash8.png",
      "spindash-mid.png"
    ],
    fps:30,
    loop:true
  },
  "died":{
    frames:[
      "died.png"
    ],
    fps:60,
    loop:true
  },
  "spring":{
    frames:[
      "spring1.png"
    ],
    fps:60,
    loop:true
  },
  "duck":{
    frames:[
      "duck.png"
    ],
    fps:60,
    loop:true
  },
  "lookup":{
    frames:[
      "lookup.png"
    ],
    fps:60,
    loop:true
  },
  "stand":{
    frames:[
      "stand.png"
    ],
    fps:60,
    loop:true
  },
  "run":{
    frames:[
      "run1.png",
      "run2.png",
      "run3.png",
      "run4.png",
      "run5.png",
      "run6.png",
      "run7.png"
    ],
    fps:50,
    loop:true
  },
  "push":{
    frames:[
      "push1.png",
      "push2.png",
      "push3.png",
      "push4.png",
      "push5.png",
      "push6.png",
      "push8.png",
      "push9.png"
    ],
    fps:30,
    loop:true
  },
  "roll":{
    frames:[
      "spin1.png",
      "spin2.png",
      "spin3.png",
      "spin4.png",
      "spin5.png",
      "spin6.png",
      "spin7.png",
      "spin8.png",
      "spin9.png",
      "spin10.png",
      "spin11.png",
      "spin12.png",
      "spin13.png",
      "spin14.png",
      "spin15.png",
      "spin16.png",
      "spin17.png"
    ],
    fps:60,
    loop:true
  }
};